#!/usr/bin/env bash
# comment line
count=1
while [ $count -le 100 ];
do
	if (( count % 5 == 0 && count % 3 == 0 )) ;
	then
		echo "FizzBuzz"
	elif (( count % 5 == 0 )) ;
        then
                echo "Fizz"
	elif (( count % 5 == 0 ));
        then
                echo "Buzz"
	fi
	else
       		echo "$count"
	((count++))
done
