#!/usr/bin/env bash
# /etc/passwd faylından username, uid və home qovluğunu oxuyur
# İkinci sətir mütləq şərh olmalıdır

while IFS=":" read -r user pass uid gid info home shell || [ -n "$user" ]
do
    echo "$user"
    echo "$uid"
    echo "$home"
done < /etc/passwd
