#!/usr/bin/env bash
# /etc/passwd faylından məlumatları oxuyur və formatlı şəkildə çap edir

while IFS=":" read -r user pass uid gid info home shell
do
    echo "The user $user has an ID $uid and a home directory $home"
done < /etc/passwd
