#!/usr/bin/env bash
# Bu skript if, elif və else istifadə edərək 10 dəfə çap edir
i=1
while [ "$i" -le 10 ]
do
    if [ "$i" -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    elif [ "$i" -gt 10 ]
    then
        # Bu hissə heç vaxt işləməyəcək, amma elif tələbini ödəyir
        echo "End"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done
