#!/usr/bin/env bash
# Bu skript Best School mesajını 10 dəfə çap edir, 9-cu dövrədə Hi əlavə edir
i=1
while [ "$i" -le 10 ]
do
    echo "Best School"
    if [ "$i" -eq 9 ]
    then
        echo "Hi"
    fi
    i=$((i + 1))
done
