#!/usr/bin/env bash
# comment line
hour_numbers=0
while [ $hour_numbers -le 12 ];
do
	echo "Hour: $hour_numbers"
	minute_numbers=1	
	while [ $minute_numbers -le 59 ];
	do
		echo "$minute_numbers"
		((minute_numbers++))
	done	
	((hour_numbers++))
done
