#!/usr/bin/env bash
# comment line
minute_numbers=1
hour_numbers=0
while [ $hour_numbers -le 12 ];
do
	echo "$hour_numbers"
	while [ $minute_numbers -le 59 ];
	do
		echo "$minute_numbers"
		((minute_numbers++))
	done
	((hour_numbers++))
done
