#!/usr/bin/env bash
# comment line
if [ -f "school" ];
then
	echo "school file exists"
	if [ -n "school" ];
	then
 		echo "school file is empty"
	else
		echo "school file is not empty"
		if [ "school" =~ ^[0-9]+$ ];
		then
			echo "school file is a regular file"
		fi
	fi
else
	echo "school file not exists"
fi

if [ -e "school" ];
then
        echo "school file exists"
        if [ -n "school" ];
        then
                echo "school file is empty"
        else
                echo "school file is not empty"
                if [ "school" =~ ^[0-9]+$ ];
                then
                        echo "school file is a regular file"
                fi
        fi
else
        echo "school file not exists"
fi
