#!/usr/bin/env bash
# comment line
if [ -e "school" ];
then
	echo "school file exists"
	if [ -f "school" ];
	then
 		echo "school file is a regular file"
		if [ -s "school" ];
		then
			echo "school file is empty"
		else
			echo "school file is not empty"
		fi
	else
		echo "school file is a directory"
		if [ -s "school" ];
                then
                        echo "school file is empty"
                else
                        echo "school file is not empty"
		fi
	fi
else 
	echo "school file does not exist"
fi
