#!/usr/bin/env bash
# Init script to manage manage_my_process

PID_FILE="/var/run/my_process.pid"
# Proses skriptinin adı (əgər eyni qovluqdadırlarsa ./ istifadə edin)
EXEC="./manage_my_process"

case "$1" in
    start)
        $EXEC &
        echo $! > "$PID_FILE"
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f "$PID_FILE" ]; then
            kill "$(cat "$PID_FILE")"
            rm "$PID_FILE"
            echo "manage_my_process stopped"
        fi
        ;;
    restart)
        # Stop hissəsi
        if [ -f "$PID_FILE" ]; then
            kill "$(cat "$PID_FILE")"
            rm "$PID_FILE"
        fi
        # Start hissəsi
        $EXEC &
        echo $! > "$PID_FILE"
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
